<?xml version="1.0"?>
<package format="3">
  <name>jetson_interfaces</name>
  <version>0.1.0</version>
  <description>Message contracts used by the Jetson perception lessons.</description>
  <maintainer email="lgy10271416@gmail.com">lgy1027</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>rosidl_default_generators</build_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>
  <depend>std_msgs</depend>

  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <!-- 接口包使用 ament_cmake 生成并安装消息代码。 -->
    <build_type>ament_cmake</build_type>
  </export>
</package>
